### PR TITLE
feature:frappe-react-indexdb

### PR DESCRIPTION
**Pull request by sumitjain236**

### CODE REVIEW

**Comment by nikkothari22** [comment]
A few points that come to my mind as of now:

1. Local storage needs to be cleared when the user is logged out. Currently the library only clears it when the user explicitly logs out using the in-built function. But a user can be logged out or account disabled by the admin from the backend. In that case, we need to check for the logged in state and clear the storage if the user is Guest.
2. Permissions can be changed by the admin for a particular user. In that case, the system needs to clear data from local storage as well. Currently we are only checking timestamp, but we need to find a way to validate whether a user has the necessary permissions to access the documents or not, and if not, it should clear the storage. We need to think this through. 

Both of the above points are critical before this can be merged. We need to ensure that we do not store data that the user does not have access to.

**Comment by sumitjain236** [comment]
> A few points that come to my mind as of now:
> 
> 1. Local storage needs to be cleared when the user is logged out. Currently the library only clears it when the user explicitly logs out using the in-built function. But a user can be logged out or account disabled by the admin from the backend. In that case, we need to check for the logged in state and clear the storage if the user is Guest.
> 2. Permissions can be changed by the admin for a particular user. In that case, the system needs to clear data from local storage as well. Currently we are only checking timestamp, but we need to find a way to validate whether a user has the necessary permissions to access the documents or not, and if not, it should clear the storage. We need to think this through.
> 
> Both of the above points are critical before this can be merged. We need to ensure that we do not store data that the user does not have access to.

Updated Code added

**Comment by sumitjain236** [comment]
> > A few points that come to my mind as of now:
> > 
> > 1. Local storage needs to be cleared when the user is logged out. Currently the library only clears it when the user explicitly logs out using the in-built function. But a user can be logged out or account disabled by the admin from the backend. In that case, we need to check for the logged in state and clear the storage if the user is Guest.
> > 2. Permissions can be changed by the admin for a particular user. In that case, the system needs to clear data from local storage as well. Currently we are only checking timestamp, but we need to find a way to validate whether a user has the necessary permissions to access the documents or not, and if not, it should clear the storage. We need to think this through.
> > 
> > Both of the above points are critical before this can be merged. We need to ensure that we do not store data that the user does not have access to.
> 
> Updated Code added

python repository : https://github.com/sumitjain236/frappe_offline.git

**Comment by tsmanagers** [comment]
Do we need to use fraape_offline app along with frappe-react SDK?

**Comment by nikkothari22** [comment]
@tsmanagers 

Caching on IndexedDB is not yet supported by the SDK. We were trying to build something similar to Replicache and Linear, but we realised that it cannot be a generic solution. (Two way real-time sync is hard) 

This is something that could just be a separate library (not dependent on Frappe at all) and should ideally be implemented based on the application.

**Pull request closed without merging**
